MINOR: fix extra broker setup
Quickstart setup for brokers 1 and 2 need "zookeeper.connect" setting.

Otherwise you are greeted with:
org.apache.kafka.common.config.ConfigException: Missing required configuration "zookeeper.connect" which has no default value.