Fixed path to log4j config file
While running the quickstart tutorial, I came across this exception due to bad file URI:

D:\gdrive\workspace\Pulse\kafka_2.11-0.10.2.0>bin\windows\kafka-server-start.bat config\server.properties
log4j:ERROR Could not read configuration file from URL [file:D:/Userfiles/my_user_dir/Downloads/kafka_2.11-0.10.2.0/kafka_2.11-0.10.2.0/bin/windows/../../config/log4j.properties].
java.io.FileNotFoundException: D:\Userfiles\my_user_dir\Downloads\kafka_2.11-0.10.2.0\kafka_2.11-0.
10.2.0\bin\windows\..\..\config\log4j.properties (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)