KAFKA-12357: Do not inline methods from the scala package by default
As mentioned in #9548, users currently use the kafka jar (`core` module)
for integration testing and the current inlining behavior causes
problems when the user's classpath contains a different Scala version
than the one that was used for compilation.

An example error:

`java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7`

We disable inlining of the `scala` package by default, but make it easy
to enable it for those who so desire (a good option if you can ensure
the scala library version matches the one used for compilation). While
at it, we make it possible to disable scala compiler optimizations
(`none`) or to use only method local optimizations (`method`). This can
be useful if optimizing for compilation time during development.

Verified behavior by running gradlew with `--debug` and checking the
output after `[zinc] The Scala compiler is invoked with:`