Disable inlining of Scala library methods.
Previously, the Scala compiler was configured to inline all usages of
symbols in under the `scala` package. This is problematic because it
means that published Kafka jars must run with the exact same version of
the Scala library that the Kafka jar was compiled with.  If the runtime
uses a different version of the Scala library then users risk getting a
crash like this:

```
java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
```

This commit disables inlining from the `scala` package to prevent
crashes like this. The downside to this change is it may introduce
performance regressions.