MINOR: Exit catcher should be reset after the cluster is shutdown (#15062)
I was investigating a build which failed with "exit 1". In the logs of the broker, I was that the first call to exist was caught. However, a second one was not. See the logs below. The issue seems to be that we must first shutdown the cluster before reseting the exit catcher. Otherwise, there is still a change for the broker to call exit.

```
[2023-12-21 13:52:59,310] ERROR Shutdown broker because all log dirs in /tmp/kafka-2594137463116889965 have failed (kafka.log.LogManager:143)
[2023-12-21 13:52:59,312] ERROR test error (kafka.server.epoch.EpochDrivenReplicationProtocolAcceptanceWithIbp26Test:76)
java.lang.RuntimeException: halt(1, null) called!
	at kafka.server.QuorumTestHarness.$anonfun$setUp$4(QuorumTestHarness.scala:273)
	at org.apache.kafka.common.utils.Exit.halt(Exit.java:63)
	at kafka.utils.Exit$.halt(Exit.scala:33)
	at kafka.log.LogManager.handleLogDirFailure(LogManager.scala:224)
	at kafka.server.ReplicaManager.handleLogDirFailure(ReplicaManager.scala:2600)
	at kafka.server.ReplicaManager$LogDirFailureHandler.doWork(ReplicaManager.scala:324)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:131)
```

```
[2023-12-21 13:53:05,797] ERROR Shutdown broker because all log dirs in /tmp/kafka-7355495604650755405 have failed (kafka.log.LogManager:143)
```

Reviewers: Luke Chen <showuon@gmail.com>