MINOR: Control plane listener tests should not use static port (#7033)
We recently saw a few failing tests recently due to the static reliance on port 5000. For example:
```
org.apache.kafka.common.KafkaException: Socket server failed to bind to localhost:5000: Address already in use.
	at kafka.network.Acceptor.openServerSocket(SocketServer.scala:605)
	at kafka.network.Acceptor.<init>(SocketServer.scala:481)
	at kafka.network.SocketServer.createAcceptor(SocketServer.scala:253)
	at kafka.network.SocketServer.$anonfun$createControlPlaneAcceptorAndProcessor$1(SocketServer.scala:234)
	at kafka.network.SocketServer.$anonfun$createControlPlaneAcceptorAndProcessor$1$adapted(SocketServer.scala:232)
	at scala.Option.foreach(Option.scala:438)
	at kafka.network.SocketServer.createControlPlaneAcceptorAndProcessor(SocketServer.scala:232)
	at kafka.network.SocketServer.startup(SocketServer.scala:119)
	at kafka.network.SocketServerTest.withTestableServer(SocketServerTest.scala:1139)
	at kafka.network.SocketServerTest.testControlPlaneRequest(SocketServerTest.scala:198)
```
This patch fixes the failing tests to dynamically select the port.

Reviewers: Ismael Juma <ismael@juma.me.uk>