Catch ClassCastExceptions caused by incorrect Serde setup
Idea here is to give better feedback to the user when their Serde
setup is incorrect. Result is:

StreamsException: ClassCastException in processor node. Are your Serdes correct? Are default Serdes specified?

Vs

ClassCastException: class [B cannot be cast to class java.lang.String ([B and java.lang.String are in module java.base of loader 'bootstrap')