KSTREAMS-3033: Fix Flaky Test QueryableStateIntegrationTest#queryOnRebalance
This is not guaranteed to actually fix `queryOnRebalance`, since the
failure could never be reproduced locally. I did not bump timeouts
because it looks like that has been done in the past for this test
without success. Instead this change makes the following improvements:

1. It waits for the application to be in a RUNNING state before
proceeding with the test.

2. It waits for the remaining instance to return to RUNNING state
within a timeout after rebalance. I observed once that we were able to
do the KV queries but the instance was still in REBALANCING, so this
should reduce some opportunity for flakiness.

3. The meat of this change: we now iterate over all keys in one shot
(vs. one at a time with a timeout) and collect various failures, all of
which are reported at the end. This should help us to narrow down the
cause of flakiness if it shows up again.

Before:

```
java.lang.AssertionError: Condition not met within timeout 120000. waiting for metadata, store and value to be non null
    at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:376)
    ...
```

After:

```
java.lang.AssertionError: Not all keys are available for store word-count-store-stream-three-0 in 120000 ms
    * No value is available for these keys: [goodbye, foo, bar]
    * Exceptions were raised for the following keys:
        Sam:
            java.lang.IllegalArgumentException: Ooops
            	at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.lambda$verifyAllKVKeys$6(QueryableStateIntegrationTest.java:289)
            	at org.apache.kafka.test.TestUtils.retryOnExceptionWithTimeout(TestUtils.java:417)
            	at org.apache.kafka.test.TestUtils.retryOnExceptionWithTimeout(TestUtils.java:385)
            	at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.verifyAllKVKeys(QueryableStateIntegrationTest.java:265)
            	at org.apache.kafka.streams.integration.QueryableStateIntegrationTest.queryOnRebalance(QueryableStateIntegrationTest.java:431)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:24)
        ...
```