MINOR: make sure all partition info is propagated (#13037)
Recently, we have some flaky tests failed with: (ex: build #1457, #1459, #1460

java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at kafka.utils.TestUtils$.describeTopic(TestUtils.scala:475)
	at kafka.utils.TestUtils$.topicHasSameNumPartitionsAndReplicationFactor(TestUtils.scala:484)

The line failed is when we tried to create a topic but got TopicExistsException, so we want to make sure this topic has the expected partition num and replication factor. It failed while trying to describe this topic, and got UnknownTopicOrPartitionException. That will happen when topic is created but the metadata haven't propagated to all brokers. So, fix it by explicitly waiting for partition info propagated to all brokers before verifying topicHasSameNumPartitionsAndReplicationFactor.

Reviewers: Ismael Juma <ismael@juma.me.uk>, dengziming <dengziming1993@gmail.com>, Justine Olshan <jolshan@confluent.io >