MINOR: Fix ClassCastException in ConsumerGroupCommand
Offset and partition are not converted from String to
long and int correctly.

Running the command line with --from-file option causes
the following exception:

java.lang.ClassCastException: java.lang.String cannot be
cast to java.lang.Integer

Reason: asInstanceOf used for the conversion.

Also, unit test is using --to-earliest and --from-file
together when executing the test. This is executing
--to-earliest option only and ignoring --from-file
option. Since the preparation part is also using
--to-earliest to create the file, this unit test
passes without testing --from-file option. Fixed
the unit test too.

Author: Erkan Unal <eunal@cisco.com>

Reviewers: Ismael Juma <ismael@juma.me.uk>

Closes #3938 from eu657/eu657-patch-1

(cherry picked from commit 71a65d95a257d98925b5f0f6f2227504cf5043a2)
Signed-off-by: Ismael Juma <ismael@juma.me.uk>