Add missing class for ZSTD in native docker image
Using the native docker image, we faced issues when trying to create a topic that has `compression_type=zstd".

That basically threw the following error, which was only disappeared when we tried to disable the compression on the topic.
```
ERROR [ReplicaManager broker=1] Error processing append operation on partition <topic_name>-<partition_number> (kafka.server.ReplicaManager)
java.lang.NoSuchFieldError: com.github.luben.zstd.ZstdOutputStreamNoFinalizer.dstPos
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1357)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:449)
	at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.resetCStream(Native Method)
	at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.close(ZstdOutputStreamNoFinalizer.java:423)
	at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.close(ZstdOutputStreamNoFinalizer.java:405)
	at java.base@21.0.2/java.io.FilterOutputStream.close(FilterOutputStream.java:193)
	at java.base@21.0.2/java.io.FilterOutputStream.close(FilterOutputStream.java:193)
```