MINOR: Improve assert in ControllerFailoverTest
It sometimes fails in Jenkins like:

```text
java.lang.AssertionError: IllegalStateException was not thrown
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at kafka.controller.ControllerFailoverTest.testHandleIllegalStateException(ControllerFailoverTest.scala:86)
```

I ran it locally 100 times with no failure.

Author: Ismael Juma <ismael@juma.me.uk>

Reviewers: Rajini Sivaram <rajinisivaram@googlemail.com>

Closes #3176 from ijuma/improve-controller-failover-assert

(cherry picked from commit 31cc8885e4cfc35d97291b5d9eece6f3793f2538)
Signed-off-by: Ismael Juma <ismael@juma.me.uk>