MINOR: Increase test producer max.block.ms in MirrorConnectorsIntegrationTransactionsTest
We've been seeing some flaky failures lately for the `MirrorConnectorsIntegrationTransactionsTest` with this stack trace:

```
org.apache.kafka.common.errors.TimeoutException: Timeout expired after 60000ms while awaiting InitProducerId
```

(We don't get any other stack frames because the Kafka `TimeoutException` class [doesn't provide them](https://github.com/apache/kafka/blob/5afdb17092f99d956bf65fcb543de0b15c04e01f/clients/src/main/java/org/apache/kafka/common/errors/ApiException.java#L45-L49)).

One example of this failure can be found [here](https://ge.apache.org/s/52il7msnknzp2/tests/task/:connect:mirror:test/details/org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationTransactionsTest/testReplicationWithoutOffsetSyncWillNotCreateOffsetSyncsTopic()?top-execution=1).

After examining the logs for one of these failures, it looks like this is either due to a broker bug, or slow CI. During a successful run of the test, it took 23 seconds for `Producer::initTransactions` to complete. It's not inconceivable that when CI load is high, it may take higher than a minute for that same method to complete, which would explain the failures we've been seeing.

In order to be resilient against slow CI, or at least rule that out as a root cause, we can bump the producer's `max.block.ms` from its default of 1 minute to a higher timeout of 5 minutes, which should give it plenty of time to complete `initTransactions`.