KAFKA-2990; Fix NoSuchMethodError in Pool with cast to ConcurrentMap
Author: Jason Gustafson <jason@confluent.io>

Reviewers: Ismael Juma <ismael@juma.me.uk>, Ewen Cheslack-Postava <ewen@confluent.io>

Closes #675 from hachikuji/KAFKA-2990

(cherry picked from commit f3fc9e108eb1e5d47144cc7f2eaa8beb4f88be6b)
Signed-off-by: Ewen Cheslack-Postava <me@ewencp.org>