MINOR: Don't register signal handlers if running on Windows
The following happens on Windows for `HUP`:

[2017-10-11 21:45:11,642] FATAL  (kafka.Kafka$)
java.lang.IllegalArgumentException: Unknown signal: HUP
        at sun.misc.Signal.<init>(Unknown Source)
        at kafka.Kafka$.registerHandler$1(Kafka.scala:67)
        at kafka.Kafka$.registerLoggingSignalHandler(Kafka.scala:73)
        at kafka.Kafka$.main(Kafka.scala:82)
        at kafka.Kafka.main(Kafka.scala)

I thought it was safer not to register them at all since the additional
logging is a nice to have and we haven't tested it on Windows.

Also changed map to be concurrent and removed stray
printStackTrace in test.

Author: Ismael Juma <ismael@juma.me.uk>

Reviewers: Damian Guy <damian.guy@gmail.com>

Closes #4066 from ijuma/dont-register-signal-handler-windows