KAFKA-18483: Disable `Log4jController` and `Loggers` if Log4j Core absent
If Log4j Core is absent, most calls to `Log4jController` and `Loggers` will end up with a `NoClassDefFoundError`.

This changeset:

- Profits from the major version bump to rename `k.util.Log4jController` to `LoggingController`.
- Removes `o.a.l.l.Level` from the signature of public methods of `o.a.k.connect.runtime.Loggers` and replaces it with `String`.
- Provides an additional no-op implementation of `k.util.LoggingController` and `o.a.k.connect.runtime.Loggers`: if Log4j Core is not present on the runtime classpath the no-op implementation will be used.